IBM/audit-ci

- README.md
> feat(badges): Added Travis-CI build badge and David dependencies badge.

- .circleci/config.yml
- README.md
> feat(circleci): Added CircleCI for test running.

- .travis.yml
- README.md
> fix(travis-pr-only): Modify README to suggest running on PR build.

- .travis.yml
> fix(travis-comment): Updated before_install comment in .travis.yml

- .circleci/config.yml
- .travis.yml
- README.md
> chore: Update README to prefer devDependency installation.

- package-lock.json
- package.json
Changes made for this release: https://github.com/IBM/audit-ci/compare/5bcf49f8..aee4817f
**Features**
- Yarn support
- Prettier styling with husky git hooks
**Bug fixes**
- Improved error uncaught exception error handling by displaying the stack trace rather than saying an unknown error occurred
No known breaking changes.
> chore: bump version to 1.2.0

- package-lock.json
- package.json
Changes made for this release: https://github.com/IBM/audit-ci/compare/2abe3577..beb57e67
**Features:**
beb57e67 - feat(advisory): Whitelist advisories (#38)
**Bug fixes:**
929b75c3 - Fix Yarn output parsing (#36)
e64f4b55 - fix(homepage): Added missing slash to homepage url.
> chore: bump version to 1.2.1

- package-lock.json
- package.json
**Bug fixes**
ee86366d1c310ffeebb414d9150e7cf63856f5f1 - Replace error checking from stderr to error #50
**Chores**
982f494a5fe3c38962a1867f3b1da241daa014e1 - Update dependencies #51
> chore(release): Patch bump to 1.3.1

- lib/audit-ci.js
Addresses: https://github.com/IBM/audit-ci/issues/55
> fix(directory): Finds package manager files when using `--directory`

- README.md
- lib/audit-ci.js
- lib/npm-auditer.js
- lib/yarn-auditer.js
- test/npm-auditer.js
- test/yarn-auditer.js
Closes the issue: https://github.com/IBM/audit-ci/issues/58
> Option to only output a summary report

- package-lock.json
- package.json
**Features**
- Add `--registry` argument (closes #46) (PR: #47)
**Fixes**
- Add `test` directory to `npm run lint` (PR: #62)
**Chores**
- Line-ending-related clean up (PR: #62)
- Bump ESLint (minor) (PR: #62)
- Bump eslint-config-prettier (patch) (PR: #62)
> chore(release): Patch release to 1.4.1

- .travis.yml
- Make the npm update and yarn install before_install for clarity
- Change cache syntax
> chore: Clean up and update .travis.yml

- package-lock.json
- package.json
> fix: Address vulnerabilities with js-yaml

- package-lock.json
- package.json
Also fixes some dependencies to being dev dependencies at depth >= 2
**Features**
- Retry mechanism for 503s #82 (closes #75)
**Chores**
- Fix advisories #83 
_Minor release due to the new behaviour of retry mechanism_
> chore: Release minor 1.7.0

- package-lock.json
- package.json
BREAKING: Change report type behaviour
> chore: Release 2.0.0

- package-lock.json
- package.json
**Bug fixes**
Fix retry mechanism for other version of NPM error message: https://github.com/IBM/audit-ci/pull/89
> chore: Release patch 2.0.1

- lib/common.js
- lib/npm-auditer.js
- lib/yarn-auditer.js
- package-lock.json
- package.json
This PR replaces the "by-line" module with "JSONStream" so that we can handle JSON output that is too large for `JSON.parse` to handle. This will resolve #96.
**Note**: This change is significant, as it changes our package dependencies. I welcome further discussion and will be periodically available this weekend to incorporate feedback.
**Side note**: this is my first PR to this project, so hello!
> Adds JSONStream for handling JSON data too big for JSON.parse

- package-lock.json
- package.json
**Fixes:**
- #97 - Adds `JSONStream` for handling JSON data too big for `JSON.parse`
- #98 - Change low vulnerability dependency test
**Docs:**
- #99 - Add `--pass-enoaudit` information to README
- #101 - Typo fix for the `--report-type`
_EDIT: #101 was added after Andy's review, but will merge with it since it's trivial._
> chore: Release 2.2.0 minor

- package-lock.json
- package.json
**Fixes:**
#112: Remove duplicate advisories from whitelisted list
> chore: Release 2.4.1

- package-lock.json
- package.json
#114 - Add current audit-ci version to output
#115 - chore(contributing): Improve testing section
> chore: Release 2.4.2

- lib/audit.js
Closes: https://github.com/IBM/audit-ci/issues/128
> fix: NPM ENOAUDIT message capturing improvements

- package-lock.json
- package.json
**Fixes:**
#129 - fix: NPM ENOAUDIT message capturing improvements
> chore: Release v2.5.1

- .eslintignore
- bin/audit-ci
- lib/audit-ci.js
- package.json
Unnecessary extra files, can use package.json
> chore: Remove /bin

- package-lock.json
- package.json
**Bugs fixes**
#159 - Remove duplicate element of advisoriesFound in summary
> chore: Release 3.1.1

- README.md
- Adds GitHub Actions to the README
- Uses `npx` everywhere for easier adoption
- Cleans up and simplifies grammar
Closes #179
> Update README for GitHub Actions, modernize it

- package-lock.json
- package.json
- #171 - Support Yarn Berry
- #172 - Bump lodash to fix NPM audit
- #177 - Bump lodash and y18n to fix NPM audit
- #178 - Specify NPM 6 in CircleCI
- #180 - Update README for GitHub Actions
> chore: Release 3.2.0, support Yarn Berry

- package-lock.json
- package.json
#175 - Add NPM 7 support (thanks @AlexHladin!)
> chore: Release 4.0.0

- package-lock.json
Regular expression denial of service - https://npmjs.com/advisories/1751
Regular Expression Denial of Service - https://npmjs.com/advisories/1677
> fix(deps): Bump glob-parent and hosted-git-info

- lib/Model.js
Fixes: https://github.com/IBM/audit-ci/issues/183
> fix: via link resolving for npm 7

- lib/model.ts
> fix: Deduplicate advisoryPathsFound

- README.md
to explain the reason about running immediatelly on checkout
> add note about executing right after checkout

- package-lock.json
- package.json
* chore: fix typo in lint:fix script by @kyletsang in https://github.com/IBM/audit-ci/pull/250
* chore(deps): Add audit-types by @quinnturner in https://github.com/IBM/audit-ci/pull/251
* docs: Add a ton of detail to allowlist documentation. by @quinnturner in https://github.com/IBM/audit-ci/pull/254
* fix: Handle unhandled promise rejections in bin by @quinnturner in https://github.com/IBM/audit-ci/pull/255
* fix: minor lint by @quinnturner in https://github.com/IBM/audit-ci/pull/256
* fix: PNPM audit registry warning by @quinnturner in https://github.com/IBM/audit-ci/pull/257
* fix: Handle NPM 7+'s message (error) response by @quinnturner in https://github.com/IBM/audit-ci/pull/258
**Full Changelog**: https://github.com/IBM/audit-ci/compare/v6.2.0...v6.2.1
> chore: Release 6.2.1

- package-lock.json
- package.json
Our CI is good enough and stable to catch issues.
> chore: remove husky and pretty-quick

- package-lock.json
- package.json
> Release 6.4.1

- .circleci/config.yml
https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/
> Update CircleCI base image

- .travis.yml
- package-lock.json
- package.json
- tsup.config.ts
I think this has to go after #309 to make tests work.
> Support ESM

- package-lock.json
- package.json
> Bump audit-types to support Yarn v4
