IBM/audit-ci

- .circleci/config.yml
- .travis.yml
- README.md
This is to ensure that breaking changes in the future are not automatically applied with @latest.
> fix(semver): Make documentation suggest installing ^1 instead of latest.

- .travis.yml
> feat(travis-cache): Include npm cache in Travis build to speed installs.

- MAINTAINERS.md
As I have completed my term at IBM, I am available for contact at my UWaterloo email address. I intend to continue maintaining this package.
For IBM-specific inquiries, contact Andy.
> chore: Change Quinn's IBM email to UWaterloo email

- .travis.yml
As discussed in https://github.com/IBM/audit-ci/issues/20, since `npm audit` is supported in Node 6, it is reasonable to support here. To ensure it is supported properly, we must add the Travis-CI build for Node 6.
This was possible due to work on https://github.com/IBM/audit-ci/pull/21
Signed-off-by: Quinn Turner <quinn.turner@edu.uwaterloo.ca>
> chore(node6): Added Node 6 to Travis-CI builds.

- .eslintrc.json
There is no need to substitute JSDoc validation since the JSDocs are for internal use only.
Addresses: https://github.com/IBM/audit-ci/issues/24
> chore(eslint): Remove deprecated valid-jsdoc

- lib/npm-auditer.js
- package-lock.json
- package.json
- Removes the Promise from `reportAudit` (which made the entire function reduce in indentation, creating a large diff)
- Instead of resolve/reject, return/throw Error and catch it in `runNpmAudit`
> fix: remove unnecessary dependency npm-audit-report

- lib/npm-auditer.js
- lib/yarn-auditer.js
Parsing the advisories is more consistent across yarn and npm auditors.
There is still a lot of duplication.
This commit simplifies consolidation in the future
> chore(npm-auditor): Make internal auditor API more consistent

- test/npm-critical/package-lock.json
- test/npm-high/package-lock.json
- test/npm-low/package-lock.json
- test/npm-moderate/package-lock.json
- test/npm-none/package-lock.json
The `package-lock.json` for NPM tests were outdated due to the yarn update.
> fix(tests): Updated npm test package-lock.json package names

- CONTRIBUTING.md
The need to sign off on commits with an email is unnecessary.
Information regarding who is the author is available on GitHub.
> docs(contributing): Removed need to sign off on commits

- lib/yarn-auditer.js
It appears that yarn (or the underlying node process abstractions) do not guarantee that each line emitted by the process will be a complete json blob.
This change buffers the output of the audit command into a single string, then splits it on newlines and parses each line. This ensures that no matter what chunks the yarn child process emits, we'll parse complete JSON blobs.
> Fix Yarn output parsing

- README.md
- lib/audit-ci.js
- lib/npm-auditer.js
- lib/yarn-auditer.js
This allows advisories to be whitelisted on a per-advisory basis instead of a per-module basis.
Addressed https://github.com/IBM/audit-ci/issues/37
Uses the `-a` or `--advisories` arg, pass in the numerical advisory ids.
Example: `audit-ci -l -a 650 651`
> feat(advisory): Whitelist advisories

- lib/npm-auditer.js
Type of change: **Bug fixing**
Does this introduce a breaking change?: **No**
This pull request tackles down the issue #49 
If something was returned to the output stream, it should be a formatted json, and it tries to parse it. In case there are issues with the output (couldn't parse the JSON) it will return an error.
If the output is empty will check for errors.
Note: You may want to move the `if (_error)` to the top, but the current approach is more optimistic and relays on the output and the output JSON.
N/A
Tested on node.js v10.15.1 and npm v6.5.0
> fix(runNpmAudit): Replace error checking from stderr to error

- package-lock.json
- package.json
- test/Model.js
- test/npm-auditer.js
- test/yarn-auditer.js
chore: Update NPM packages
- eslint minor
- mocha major
refactor: Move mocha tests to `test`
- NPM package now do not contain test files (previously they did since `npm pack` would pack the `lib/*.test.js` files)
- Only use root test path `test/*.js` to avoid js in test/*/node_modules
> chore: Update dependencies and move test files

- package-lock.json
- package.json
Diff: https://github.com/IBM/audit-ci/compare/v1.3.1..d2a4ac60
**BREAKING CHANGES**
- The new default output is the summary report rather than the full report.
**Features**
- Unit testing (closes #4) (PR: #53, #54)
- Add `--directory` argument (closes #17) (PR: #53, #56)
- Add option to output summary report (closes #58) (PR: #59)
**Chores**
- Use `spawn` rather than `exec` for NPM (closes #48) (PR: #53)
- Bump ESLint (minor)
> chore(release): Minor bump to 1.4.0

- README.md
- lib/audit-ci.js
- lib/npm-auditer.js
- lib/yarn-auditer.js
- package.json
- test/Model.js
- test/npm-auditer.js
- test/yarn-auditer.js
From @memelet:
> When using a private repo like nexus that does not response correctly to audit, its necessary to use --registry=https://registry.npmjs.org.
This PR supports specifying a registry for NPM (Yarn [is not supported yet](https://github.com/yarnpkg/yarn/issues/7012)) by adding the `--registry` argument. It is an optional parameter, defaulting to the package manager's standard registry.
Addresses: https://github.com/IBM/audit-ci/issues/46
> feat(registry): Add support for specifying registry

- .eslintignore
- .prettierrc
- package-lock.json
- package.json
Dependency updates:
- eslint minor
- eslint-config-prettier patch
Code changes:
- Lint the test folder
- Lint ignore all node_modules, not just the root one
- "eslint-config-prettier added: linebreak-style.
Use Prettier’s end-of-line option instead."
Not sure if .editorconfig is setting LF with eslint-config-prettier.
Adding potentially redundant LF config setting just in case.
> fix(lint): A variety of lint-related fixes

- package-lock.json
- package.json
**Fixes**
- Handle non-JSON Yarn audit report (closes #45) (PR: #66)
**Chores**
- Address advisories (closes #67) (PR: #68)
- Bump Semver (major) (PR: #68)
- Bump eslint (patch) (PR: #68)
_Minor release due to the new behaviour of Yarn non-JSON audit report_
> chore(release): Minor release to 1.5.0

- README.md
- lib/Model.js
- lib/audit-ci.js
- lib/common.js
- lib/npm-auditer.js
- lib/yarn-auditer.js
- test/Model.js
- test/npm-auditer.js
- test/yarn-auditer.js
`audit-ci.json` files that contain advisories can become outdated when dependencies are updated. What once was a vulnerable package may not be anymore.
Advisories that are whitelisted that are not found should likely be removed from the whitelist for cleanliness and reducing the risk of whitelisting an unacknowledged advisory for another module.
This changes existing behaviour, as the setting defaults to `true`.
Closes: #70
> feat: Warn when whitelisted advisories are not found

- README.md
`show-whitelisted-advisory` should be `show-not-found`.
> docs(config): Fix config example

- lib/yarn-auditer.js
- test/yarn-auditer.js
- test/yarn-error/error-message.js
- test/yarn-error/yarn
> Print yarn's output when it crashes with an error

- package-lock.json
- package.json
**Features**
- Warn when whitelisted advisories are not found (closes #70) (PR: #73)
**Fixes**
- Handle non-JSON Yarn audit report (re-closes #45) (PR: #66 and #76)
- Fix broken link in README (PR: #78) 
**Chores**
- Update `.travis.yml` config to use the `cache: npm` shortcut and provide more docs (PR: #79)
- Fix advisories (fixes #67) (PR: #68 and #80)
- Bump Mocha (minor) (PR: #80)
- Bump ESLint (minor) (PR: #80)
_Minor release due to the new behaviour of Yarn non-JSON audit report and warning when whitelisted advisories are not found_
> chore(release): Minor release to 1.6.0

- lib/audit.js
Hello!
In a previous comment https://github.com/IBM/audit-ci/issues/86#issuecomment-496798003 I talked about the retry mechanism that seemed broken for my project using NPM.
After taking a quick look, I saw that the error message given by NPM is not the same for me:
```
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.org/) does not support audit requests, or the audit endpoint is temporarily unavailable.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-05-20T12_16_22_839Z-debug.log
```
At the end of the second line, `, or the audit endpoint is temporarily unavailable` is added compared to what is compared in the retry mechanism. To make it work for both cases, I just removed the dot at the end.
What do …
> Fix retry mechanism for other version of NPM error message.

- package-lock.json
- package.json
**Features**
#88 - Added `--pass-enoaudit` flag to mitigate issues with registries having service unavailability
> chore: Release 2.1.0 minor

- test/npm-auditer.js
- test/npm-low/package-lock.json
- test/npm-low/package.json
- test/yarn-auditer.js
- test/yarn-low/package.json
- test/yarn-low/yarn.lock
`lodash` now has high vulnerabilities, so the test is incorrect. `merge` has a low vulnerability.
> Change low vulnerability dependency test

- README.md
- lib/Model.js
- lib/audit-ci.js
- package-lock.json
- test/Model.js
- test/npm-auditer.js
- test/npm-whitelisted-path/package-lock.json
- test/npm-whitelisted-path/package.json
- test/yarn-auditer.js
Hello Quinn,
I worked on the `path-whitelist` option to whitelist only specific paths of dependencies to prevent having too broad exceptions. I am working currently on the warning when a whitelisted path is specified in the configuration but does not match an actual path.
In the mean time, what do you think about the feature? Please tell me if the formatting, the tests, or anything else is not correct and should be improved.
Cheers
> Add "path-whitelist" option.

- lib/audit.js
Fix for 107 Issue
pass-enoaudit flag fails integration if registry does not return ENOAUDIT which is the expected behavior
> pass-enoaudit issue fix, IssueID:107

- package-lock.json
- package.json
**Features:**
#104 - Add "path-whitelist" option
**Fixes:**
#108 - Fix `--pass-enoaudit` to not always pass an audit
**Docs:**
#101 - README typo fix for the --report-type
#105 - Aditional examples for path whitelisting
> chore: Release 2.3.0

- lib/common.js
- package-lock.json
- package.json
Our audit-ci was failing with an error like this:
```
yarn run v1.17.3
$ node_modules/audit-ci/bin/audit-ci --config yarn-audit.json
Yarn audit report summary:
{
"vulnerabilities": {
"info": 0,
"low": 0,
"moderate": 1,
"high": 15,
"critical": 0
},
"dependencies": 12345,
"devDependencies": 0,
"optionalDependencies": 0,
"totalDependencies": 12345
}
Vulnerable whitelisted advisories found: [__LIST_OF_WHITELISTED_ADVISORIES__].
Failed security audit due to high vulnerabilities.
Exiting...
error Command failed with exit code 1.
```
To find out, which vulnerability was new, I needed to dig down into the list of whilelistes ones and see which advisory is not listed there. BUT I also needed to run `audit-ci` without summary, as otherwise I would not get a list of all vulnerabilities.
The idea …
> Add list of advisories to failed summary output

- lib/Model.js
- lib/common.js
- test/Model.js
This change, removes duplicate whitelisted advisories from the output.
It makes the whitelist more usable, when there are many exactly the same occurrences.
```
...
"whitelistedAdvisoriesFound": [2, 3, 6, 6]
...
```
Turns into
```
...
"whitelistedAdvisoriesFound": [2, 3, 6]
...
```
AND the whitelist summary info is now sorted by ids as well, and not sorted by occurences.
> Remove duplicate advisories from whitelisted list

- lib/npm-auditer.js
- lib/yarn-auditer.js
This adds the current `audit-ci` version in npm and yarn output like so:
```
audit-ci version: 2.4.1
Yarn audit report results:
...
```
```
audit-ci version: 2.4.1
NPM audit report results:
...
```
> Add current audit-ci version to output

- .circleci/config.yml
- .travis.yml
- Update CircleCI's Node.js language version to 12.15
- Remove the manual global installation of Yarn in Travis-CI and CircleCI build configs (responsible for https://circleci.com/gh/quinnturner/audit-ci/142)
> fix(CI): Update CircleCI and Travis-CI build configs

- lib/audit-ci-version.js
- lib/npm-auditer.js
- lib/yarn-auditer.js
- test/audit-ci-version.js
- test/npm-auditer.js
- test/yarn-auditer.js
Instead of performing a network call to a registry, get the audit-ci version from the package.json
Closes: #119
> fix: Get audit-ci version from package.json

- .circleci/config.yml
Only support `audit-ci` audit checks on PR builds.
Otherwise, the following scenario can occur:
1. Push a new feature with PR, but master has new vulnerabilities, breaking the PR
2. Create a fix PR with the new advisories, merge PR into master
3. Re-run the feature workflow
The expected behaviour: pass
The current behaviour: fail
This changes the behaviour to be a pass.
Closes #69
> fix(CI): audit-ci checks in CircleCI on PR builds

- README.md
Investigation has shown little adoption for the PR-only audit.
Since many projects push to master directly, it doesn't make sense to suggest using PR-only audits without explanation. Instead, both options are clearly documented now.
> docs: Change suggested usage to include master

- README.md
- lib/audit-ci.js
Deprecated one year ago: https://github.com/IBM/audit-ci/pull/74.
In the release notes, will include:
> **[BREAKING]** - The `'r'`, `'report'`, `s`, and `'summary'` options have been removed. Use `--report-type important` _[default]_ to show only relevant information, `--report-type full` to show the full audit report, or `--report-type summary` to only how the summary of the audit report.
Fun fact, it's a complete coincidence that the original PR to deprecate the options was created exactly one year ago today. As we plan on releasing a few breaking changes in `v3`, I thought it would be an appropriate time to deprecate the options. Good timing!
> [BREAKING] Remove deprecated report and summary options

- .circleci/config.yml
- .prettierrc
- .travis.yml
- README.md
- audit-ci.json
- bin/audit-ci
- lib/Model.js
- lib/audit-ci-version.js
- lib/audit-ci.js
- lib/audit.js
- lib/common.js
- lib/npm-auditer.js
- lib/yarn-auditer.js
- package-lock.json
- package.json
- test/Model.js
- test/audit-ci-version.js
- test/npm-500/npm
- test/npm-auditer.js
- test/yarn-503/yarn
- test/yarn-auditer.js
This PR does two things:
1. Drop support for Node 6 (introduces spread operator, ES2017 commas, and updates dependencies)
1. Reformats the project using a Prettier config closer to the default
- As per [their documentation](https://prettier.io/docs/en/option-philosophy.html), it's not in their philosophy to introduce extra configuration options for styling (single quotes, commas). Rather than fight their decision, just use their defaults. However, still use LF file ending for consistency across Windows and others OSes.
I do not intend to merge this quickly, as I am open to discussion as to whether dropping Node 6 support is an appropriate step for the project.
Closes: https://github.com/IBM/audit-ci/issues/125
> chore: Drop node 6 and default Prettier configs

- package-lock.json
- package.json
- #131 **BREAKING**: Drop node 6 support
- #138 **BREAKING**: Remove deprecated report and summary options
- #131 Change prettier settings
- #139 Use async/await syntax
- #139 Possibly fix https://github.com/IBM/audit-ci/issues/139
- #137 Use npmpublish GitHub Action for releases
> chore: Release 3.0.0

- lib/npm-auditer.js
> fix: say `NPM` instead of `Yarn` when using npm for full audit report

- package-lock.json
- package.json
- #145: Say NPM instead of Yarn when using npm for full audit report
> chore: Release 3.0.1

- README.md
- audit-ci.json
- lib/Model.js
- lib/allowlist.js
- lib/audit-ci.js
- lib/common.js
- lib/npm-auditer.js
- lib/yarn-auditer.js
- test/Model.js
- test/common.js
- test/npm-allowlisted-path/package-lock.json
- test/npm-allowlisted-path/package.json
- test/npm-auditer.js
- test/npm-low/package-lock.json
- test/npm-low/package.json
- test/yarn-auditer.js
- test/yarn-low/package.json
- test/yarn-low/yarn.lock
- test/yarn-none/package.json
This PR does quite a few things:
- Supports new argument `allowlist`
merges: advisories, whitelist, and path-whitelist into one argument
- Deprecates advisories, whitelist, and path-whitelist
- Warns the user to update to allowlist
- Adds new argument `show-found`
to allow config for whether to show when found a vuln
- Change low vuln test to have a path
- Adds more warnings to consider not allowlisting
- Adds additional tests
Technically, this is not a breaking change.
This is because we gracefully handle the `-a` flag.
The implementation now has a superset of functionality.
Closes https://github.com/IBM/audit-ci/pull/153
Closes https://github.com/IBM/audit-ci/issues/151
Closes https://github.com/IBM/audit-ci/issues/150
> feat(allowlist): Change default to allowlist

- package-lock.json
- package.json
- feat(allowlist): Change default to allowlist (#154)
- chore: Add Node 14 to testing matrix (#155)
- chore: Ran npm upgrade (#156)
- chore: Remove /bin (#157)
Note, none of these are technically breaking existing code, so it's a _minor_ update. However, there will be warning for all existing implementations to suggest to migrate towards the new `allowlist` argument.
> chore: Release 3.1.0

- lib/Model.js
- test/Model.js
This is a followup to #112
Is removes duplicate advisory ids from the summary. 
We cannot go the same route as in #112 as the advisoriesFound are stored as complete hash and not just the advisory.id.
This just removes any duplicate ids from the summary.
Before:
```
Vulnerable advisories are: 1227, 1227
```
After:
```
Vulnerable advisories are: 1227
```
> Remove duplicate element of advisoriesFound in summary

- CONTRIBUTING.md
- lib/Model.js
- lib/audit-ci.js
- lib/common.js
- lib/npm-auditer.js
- lib/yarn-auditer.js
- test/Model.js
- test/npm-auditer.js
- test/yarn-auditer.js
The LICENSE is always attached with the project, it's redundant to include the license in the headers. Have had no issues with missing headers in many existing files.
> chore: Remove SPDX header

- package-lock.json
Not affected by advisory 1523 https://www.npmjs.com/advisories/1523
> chore: Bump lodash to fix npm audit

- package-lock.json
Addresses:
```
➜  audit-ci git:(master) ✗ npm audit
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ y18n                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ yargs                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ yargs > y18n                                                 │ …
```
> fix: run npm audit fix, lodash & y18n

- .circleci/config.yml
Fix CircleCI broken build due to incompatibilities with NPM 6 and NPM 7: https://app.circleci.com/pipelines/github/IBM/audit-ci/216/workflows/d9e0450a-7abc-47c4-8ec1-f092ffadc09d/jobs/191
> fix(circleci): Specify NPM 6

- README.md
- lib/Model.js
- lib/allowlist.js
- lib/common.js
- lib/yarn-auditer.js
- test/Model.js
- test/common.spec.js
- test/npm-auditer.js
- test/npm7-auditer.js
- test/yarn-auditer.js
- test/yarn-config-file/audit-ci.json
**Background:**
Two of our allowlist entries changed their npm-number 4 times in the last 48 hours!!!
This is a **BREAKING CHANGE** as the identifier that is used to identify advisories is being changed from numerical npm-identifier to string github-identifiers e.g. `GHSA-rvg8-pwq2-xj7q`
Making this backward compatible is for couple of reasons not good:
1. npm-identifiers are **NOT** constant
2. npmjs.com does not use the identifiers in the `url` attribute of the json response
3. mix of numerical and string identifiers would need to be supported (in my opinion)
4. makes this package very complex
~~NOTE: I bases this change not on `IBM:main` but `quinnturner:node-12` branch so it has some changes not related to the pull-request in it. That was needed to make tests~~ 🟢  ~~which they are …
> Switch identifier to be taken from `github_advisory_id`

- .circleci/config.yml
- .travis.yml
- README.md
- audit-ci.json
- audit-ci.jsonc
- lib/audit-ci.js
- test/npm-config-file/audit-ci-with-comment.jsonc
- NPM now supports flags like --moderate.
Therefore, audit-ci's main differentiator is to use a config file
with allowlist.
Currently, our documentation pushes towards using the CLI.
Instead, prefer to show examples using a config file.
- Convert audit-ci.json -> audit-ci.jsonc
> Recommend JSONC instead of CLI args

- lib/common.ts
- lib/config.ts
- lib/model.ts
- test/common.js
- test/model.spec.js
- test/npm-auditer.spec.js
- test/npm7-auditer.spec.js
- test/yarn-auditer.spec.js
Probably the most requested feature and biggest issue with this package.
No more!
> feat: Print path for vulnerable advisories

- lib/audit-ci.ts
- lib/audit.ts
- lib/bin.ts
- lib/common.ts
- lib/config.ts
- lib/model.ts
- lib/npm-auditer.ts
- lib/yarn-auditer.ts
- package-lock.json
- package.json
- test/yarn-auditer.spec.js
- Simplifies the `AuditCiConfig` type
- Creates `dist/bin.js` instead of reusing `dist/audit-ci.js`; prep for programmatic usage
- Add `@types/chai`
> Type improvements and better functional structuring

- package.json
Randomly stumbled on this 😄 
There were 2 `.ts` extensions in the command
> chore: fix typo in lint:fix script

- README.md
Thank you to https://github.com/andrewdetorres for suggesting to update the
allowlist documentation. It's clear that the examples were insufficient at
explaining allowlisting.
> docs: Add a ton of detail to allowlist documentation.

- lib/bin.ts
When using Node 12/14 + allowlisting using the old advisory format, the pipeline unexpectedly passes because Node 12/14 does not throw an error with unhandled promise rejections.
Now, instead, we handle promise rejections at the root and explicitly `process.exit(1)`.
I found this out by looking at a community project:
https://github.com/brave-intl/publishers/runs/6428625498?check_suite_focus=true
This is the before-and-after of the change:
I am considering releasing this with a patch version bump.
> fix: Handle unhandled promise rejections in bin

- lib/npm-auditer.ts
- package-lock.json
- package.json
- test/npm7-auditer.spec.js
(Hopefully) closes https://github.com/IBM/audit-ci/issues/247.
> fix: Handle NPM 7+'s message (error) response

- lib/audit-ci-version.ts
We've never received a report for this.
> chore: Remove can't find package.json warning.

- lib/index.ts
- package.json
Now, you can interact with audit-ci using code! I haven't written the documentation for this yet.
Also, since this is the first release of programmatic usage, the API is not expected to stay stable.
This current API is mostly for early adopters and to get quick feedback.
Note, I started exporting types in this PR: #270
Closes #212 (but should create a new ticket to document the API)
> feat: Add support for importing audit-ci

- .github/workflows/codeql-analysis.yml
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
> chore: Update CodeQL

- README.md
- lib/allowlist.ts
- lib/config.ts
- lib/nsp-record.ts
- test/allowlist.spec.js
- test/npm-auditer.spec.js
- test/npm7-auditer.spec.js
- test/nsp-record.spec.js
- test/pnpm-auditer.spec.js
- test/yarn-auditer.spec.js
Closes #277
Closes #278
Finishes the implementation from #279
@quinnturner I've integrated your code and made some changes so that it wouldn't be considered a breaking change to users who consume the API.  Inside the `Allowlist` class I stored the `NSPRecord`s under different fields.  Ultimately, string ids are still used around the library, so pre-processing them and storing them still sounded like a good idea. The `NSPRecord` fields aren't currently used, but they are stored in case API users need them.
Let me know if that approach works.
For now I've only added unit tests for the smaller functions in the implementation.  If the approach above looks good, I'll add additional tests for the full audit.
> feat: implement allowlist records

- .c8rc.json
- lib/pnpm-auditer.ts
- test/pnpm-auditer.spec.js
Related to this issue: https://github.com/IBM/audit-ci/issues/292.
> Added support for registry flag for pnpm
